_target_: model.SummaryModule

model_name_or_path : skt/kogpt2-base-v2
model_type : gpt
max_context_seq_len : 512
max_label_seq_len : 30
learning_rate : 2e-5
adam_epsilon : 1e-8
warmup_ratio : 0.01
weight_decay : 0.01
num_workers : 1
top_k : 30
top_p : 0.92
temperature : 0.7